### ISSUE TITLE
not able to access Retail APIs using Managed Identity/Client Secret

### ISSUE THREAD

**Issue by nikithaatla** [microsoft/Dynamics365Commerce.Solutions#45]
Not able to create Order using Retail APIs with Managed Identity/Client Secret 
we are trying to create order using commerce APIS with Managed Identity and Client Secrets. Cart flow is used to create order, but first step create cart is failing.

1) Client Secret to create Cart using ICartManager Create method

    error
![image](https://user-images.githubusercontent.com/88876701/231040687-eeec9d68-c670-4cce-aa8f-b8abb931cf4d.png)
 

2) Managed Identity to create Cart using ICartManager Create method

  error 
 
![image](https://user-images.githubusercontent.com/88876701/231040735-51da231c-c952-4c01-bc06-6a75f995cf82.png)

It would be good if you can help us to create order using Managed Identity.

Also, we are having  trouble to use POST Sales Order API. Could you please share samples ? 

Note: able to create orders passing username and password

**Comment by madyke** [comment]
I discussed this with the CSU team, and they said this is a very rare customer scenario, which is why we don't have any samples in this area. We can put this sample request on our backlog.

If you still need assistance with specific questions in this area, please reopen the issue with details and we can have the CSU team take a look.
