### ISSUE TITLE
POS Datalist emptyDataListTemplateId & autoSelectFirstItem

### ISSUE THREAD

**Issue by emishura** [microsoft/Dynamics365Commerce.Solutions#60]
Hello,

Previously DataList had the emptyDataListTemplateId and autoSelectFirstItem properties out-of-box. But I can't find them in Commerce SDK DataList.
Do you have the plan to implement it?

**Comment by lukedgr** [comment]
Hi @emishura , for "autoSelectFirstItem" we do not plan to implement this option in the CommerceSDK data list interface because the same behavior can be implemented using the selectItems method after the datalist has loaded the data.

For the "emptyDataListTemplateId", we do not have plans to implement this functionality in the short term, but if it is critical for your customization please consider filing an extension request as outlined [here](https://learn.microsoft.com/en-us/dynamics365/fin-ops-core/dev-itpro/extensibility/extensibility-requests).
